# Generated by Django 5.0.2 on 2024-03-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("reply", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="WebsiteSnapshot",
        ),
    ]
